### ISSUE TITLE
backup to nextcloud directory isnt working

### ISSUE THREAD

**Issue by manuelautomatisch** [beemdevelopment/Aegis#1061]
### Version

2.1.2

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Onenplus 7 Pro

### Android version

Android 11

### Steps to reproduce

1. go into settings
2. select backups
3. select nextcloud directory (/data/backups/aegis)
4. manually trigger backup
5. error occurs

When I select the root directory from my nextcloud server as backup folder the backup is working fine.

### What do you expect to happen?

1. be able to backup the aegis vault to the nextcloud directory

### What happens instead?

the following error occurs:
com.beemdevelopment.aegis.vault.VaultRepositoryException: java.io.FileNotFoundException:
Error downloading file:
<file name>

### Log

I already tried the steps from https://github.com/beemdevelopment/Aegis/issues/610 but that didnt worked as well.

**Comment by alexbakker** [comment]
Could you capture a log using ADB of you reproducing the issue and share it here?

**Comment by manuelautomatisch** [comment]
Yeah sure. I will do that and post the output here.

**Comment by manuelautomatisch** [comment]
Short update: at the moment the backup is running to the root folder of nextcloud and it works good for me. Probably I will use it like that.
Although to solve the issue for those who are facing the same I will provide the logs for further analysis when I have time for it (could take a bit longer).

**Comment by manuelautomatisch** [comment]
I finally was able to collect the logs while reproducing this issue

The backup files in the nextcloud directory were created but other than the working backup files, these are empty:

![grafik](https://user-images.githubusercontent.com/79138630/210361511-d55a84f3-a5ac-4c7b-aa34-5bf3446d0846.png)

[logs.txt](https://github.com/beemdevelopment/Aegis/files/10336723/logs.txt)

**Comment by joshtrichards** [comment]
@manuelautomatisch Just a bystander here, but what version of the Nextcloud Android client is (or was) that with? There was a weird upload issue fixed around the 12/12/2022. The fix got backported to v3.23.1 (which was released on 12/21/2023) so it's possible that was mixed into things for you. Can you confirm the issue happens with Nextcloud's Android v3.23.1 client?

I'm running v3.23.1 and seeing no issues with backups, but I semi-recall backings briefly being broken for me but it was fixed by the time I got around to looking into it.

**Comment by manuelautomatisch** [comment]
@joshtrichards Thanks for the notice. I tried it again but unfortunetly the problem still occur although I'm using nextcloud v3.23.1. I'm not sure if there is a problem because the path is a external data store which I mounted with smb to nextcloud. It would wonder me if this is a problem but it is working in the root folder and also in other folders which are on the server itself and not on an external datastore.

**Comment by alexbakker** [comment]
@OlJohnny I agree that we should looks for ways to be more careful with backup pruning. Normally one wouldn't have to worry if writing, flushing and closing a file completes without errors. But SAF is not a normal filesystem.

We can't actually test whether the file ended up at the remote location correctly though. Best we could do is try to read back the file and see if it matches with what we thought we wrote to it, but there's a good chance that the documents provider is serving it from the local cache instead of fetching it from the (in this case Nextcloud) server.

**Comment by scheinercc** [comment]
Not sure if it is directly related: I also set the backup directory to a folder inside my Nextcloud root. When clicking in Aegis -> Backups -> "Directly for backup files", I can see the auto-generated files in the file explorer being in the correct folder. I also checked their content in a JSON viewer. 
But checking my NC the files are not there. Not in the Android app nor on the server.

**Comment by alexbakker** [comment]
I think we can conclude that this is most likely an issue in Nextcloud, not in Aegis. Based on a quick search, there appears to be some history of uploads not getting triggered in Nextcloud: https://github.com/nextcloud/android/issues/9320#issuecomment-991918596.

As I said previously, we could try to read back the file we just wrote to Nextcloud's documents provider, but in all likelihood we'd just be reading the file back from the local cache instead of the remote Nextcloud server.
