### ISSUE TITLE
Unable to manually reorder after removing groups

### ISSUE THREAD

**Issue by Avrution** [beemdevelopment/Aegis#1704]
### Version

3.4.1

### Source

Google Play

### Vault encryption

Yes (with biometric unlock)

### Device

Oneplus 7T

### Android version

14

### Steps to reproduce

Long press entry
No move option or ability to change order

### What do you expect to happen?

Be able to change the order in Custom sort mode.

This was supposedly locked out if you had groups enabled, but even if you delete all groups the sorting ability doesn't return.

### What happens instead?

Only the other options are available

**Comment by michaelschattgen** [comment]
Ah you can disregard my comment in #1418. It seems like you're running into a bug because this should definitely be possible still. Could you send us a screenshot or perhaps even a screen recording of what you're trying to achieve? Please make sure there's no sensitive information in it.

Unless you are in a rare corrupt state you should be able to re-order entries when no groups are selected and your sorting is set to custom.

**Comment by Avrution** [comment]
Well, the screen recording wouldn't be helpful since it won't show me trying to drag the entry.  

No way to move the entry.  I can only select it and make changes using the upper menu

![Image](https://github.com/user-attachments/assets/bc753f7c-d60e-4d23-bb87-5d5ff47005b5)

**Comment by michaelschattgen** [comment]
>Well, the screen recording wouldn't be helpful since it won't show me trying to drag the entry.

Believe it or not, it often gives us more context than you think.


Thank you for the screenshot though. I can't for the life of me seem to reproduce this and the only time we stop a user from dragging around an entry in this scenario is when the sorting is not set to 'Custom', a groupfilter is set or the searchfilter is enabled. If you're sure this is not the case then I advise you to play around with creating a new group, set the group filter to be that group and then untoggle it again. This should reset the groupfilters state (if that was the issue here to begin with) and you hopefully should be able to drag entries around again.

**Comment by Avrution** [comment]
That seemed to fix it.  It has been like this for months, so it seems that groupfilters state has been stuck all this time!

**Comment by michaelschattgen** [comment]
Ah happy to hear that that solved the issue for you! I will play around and try to see if I can reproduce this but it's entirely possible this is already fixed in the current version. Sorry for the inconvenience.

**Comment by thwismer** [comment]
Hi everyone, so this has bothered me for some time: I can't reorder any items. I long press on Android on an entry but the only thing that happens is ti gets selected with the tick symbol. Is this a bug or am I just not getting it?

**Comment by neclimdul** [comment]
"a groupfilter is set" this bit me. Grouping made the lists manageable to drag so without any feedback to the contrary it seemed the logical place to do it.

**Comment by thwismer** [comment]
What do you mean by that? I dont follow. For me it still does not work.

**Comment by neclimdul** [comment]
Yeah sure it was kinda confusing. Make sure all the group filters are unselected. Like if you have a "coding" group, select then unselect it. Now all the groups should just be borders and you should see both grouped and ungrouped entries. You should also be able to select them and drag them.

Note, you will still select them (get a check), but you'll also be able to drag them.
