### ISSUE TITLE
[Resource] I made some 2FA profile icons

### ISSUE THREAD

**Issue by krisu5** [beemdevelopment/Aegis#63]
![Icon Preview](https://user-images.githubusercontent.com/3540275/56386049-77869280-6229-11e9-8cd7-9fb5903749b0.png)

Icons are 1024x1024, using [simpleicons.org](https://simpleicons.org/) as resource for most of the icons (for others, I used official branding resources) and main brand color as background color. Nothing fancy, just pasting SVGs and placing the BG color.

I started making icons for own use, but I figure why not make more of them as easy icon resource. I made icons based of the [Two Factor Auth List](https://twofactorauth.org/) and is the site / service popular enough to make a icon IMO.

I can make more by request (include vector / branding sources, if possible).

**[See and download some / all icons here (has new and updated icons)](https://drive.google.com/drive/folders/14pLZVLUw4FsC9zoQtuMnnA2gBXKYUCyW)** or [download the ZIP hosted in GitHub](https://github.com/beemdevelopment/Aegis/files/3095897/Aegis.2FA.Profile.Icons.zip) (older, doesn't have updates nor new icons).

[Source files are here (Adobe Illustrator)](https://drive.google.com/drive/folders/1ejlBQoxbh8oe7cbvHeu9dnvB0dcXSekD)

**Mobile Screenshot**

![Screenshot_20190418-221723](https://user-images.githubusercontent.com/3540275/56386738-4b6c1100-622b-11e9-9349-562fec48cde4.png)

**Comment by alexbakker** [comment]
Awesome! Thanks for sharing your work. These fit perfectly in Aegis' simple
design. 

We're still thinking about the best way to support a default list icons in the
app. There are a number of options: 
1. Embed the icons into the app
2. Create a separate app just for the icons and expose/retrieve them through a
   ContentProvider
3. Host the icons on a CDN and let clients download the ones they need

Whichever option we pick, we also have to think about the maintenance burden of
having a default list of icons. I want to avoid ending up in the situation that
andOTP is in, where most of the issues and pull requests are for icons.

Looking at simpleicons.org, it seems that all of the icons are SVGs with a
background color. Would it be easy to automatically create the icons based on
that? It sounds as simple as taking the existing SVG and adding a circle as the
background, but I don't have a whole lot of experience on this space, so correct
me if I'm wrong.

**Comment by krisu5** [comment]
> Whichever option we pick, we also have to think about the maintenance burden of
having a default list of icons. I want to avoid ending up in the situation that
andOTP is in, where most of the issues and pull requests are for icons.

Yeah, I agree. It's kind of mess right now.

> Looking at simpleicons.org, it seems that all of the icons are SVGs with a
background color. Would it be easy to automatically create the icons based on
that? It sounds as simple as taking the existing SVG and adding a circle as the
background, but I don't have a whole lot of experience on this space, so correct
me if I'm wrong.

TBH, I'm not sure because I lack developer skills, I'm more of designer myself. I don't have knowhow to automate this. Few of the logos have been visually centered based of my eye, so that's harder thing to automate I think.

And simpleicons.org still lacks lot of icons. Like LastPass, 1Password and Bitwarden. Those had to get from the official branding pages and sometimes edit them.

**Comment by ByteHamster** [comment]
> Host the icons on a CDN and let clients download the ones they need

I strongly vote against that. The first thing I did while looking for a new OTP app was checking if it needs network permissions.

> Create a separate app just for the icons and expose/retrieve them through a
ContentProvider

With that option, most users probably will not download the icon package

> I want to avoid ending up in the situation that
andOTP is in, where most of the issues and pull requests are for icons.

Maybe you could create a second repo that only contains the icons. That other repo is then integrated (via git submodule or gradle dependency) into the main app. You can make use of [multiple issue templates](https://github.blog/2018-01-25-multiple-issue-and-pull-request-templates/): when creating an issue, users have to select what they want to report before writing anything. Add one that says "Icon request" and then clearly state that icons are handled in the other repo.

**Comment by ByteHamster** [comment]
Extending that idea, maybe you can even collaborate with andOTP and create a common icon library that both apps can use.

**Comment by nchristensen** [comment]
> Extending that idea, maybe you can even collaborate with andOTP and create a common icon library that both apps can use.

I think this is a good idea.

**Comment by alexbakker** [comment]
@krisu5

> TBH, I'm not sure because I lack developer skills, I'm more of designer myself. I don't have knowhow to automate this. Few of the logos have been visually centered based of my eye, so that's harder thing to automate I think.

I've started experimenting with this in [a separate repository](https://github.com/alexbakker/aegis-icons/tree/master/icons). Some of the icons have small alignment issues, but most look fine in my opinion. I think this would be a good way to hit the ground running with a bunch of icons. Small issues like alignment can be fixed later, as all of the icons are SVG's anyway.

@ByteHamster 

> I strongly vote against that. The first thing I did while looking for a new OTP app was checking if it needs network permissions.

Yeah, we don't really like this option either. The icons are either going to be included with the app itself or with a separate app.

> With that option, most users probably will not download the icon package

Could you elaborate on this one? Users seem fine with downloading separate apps to get stickers for WhatsApp. Why wouldn't this work for Aegis?

The reason why we're thinking about distributing the icons through a separate app, is to keep our app as small as possible. This is not a very big concern if we're only using SVG's, but if we also start including PNG's the app will quickly increase in size.

**Comment by ByteHamster** [comment]
> Users seem fine with downloading separate apps to get stickers for WhatsApp. Why wouldn't this work for Aegis?

I did not even know that you can download stickers for WhatsApp :D Maybe you can add a popup that advertises the icon package, so users know that it exists.

**Comment by rmunozrodriguez** [comment]
Very good icons @krisu5, I like them. Personally I miss Synology, TeamViewer and Tutanota. Any news about the inclusion of a default icon list in the app?

**Comment by krisu5** [comment]
> Personally I miss Synology, TeamViewer and Tutanota. 
Done. [Downloadable from GDrive](https://drive.google.com/drive/folders/14pLZVLUw4FsC9zoQtuMnnA2gBXKYUCyW).

**Comment by rmunozrodriguez** [comment]
> 
> 
> > Personally I miss Synology, TeamViewer and Tutanota.
> 
> Done. [Downloadable at GDrive](https://drive.google.com/drive/folders/14pLZVLUw4FsC9zoQtuMnnA2gBXKYUCyW).

Thank you!

**Comment by MRVMV** [comment]
I don't think its good decision to make another app just for icons, it will surely better for me to just download an icon pack zip and choose icons by myself than adding a whole app just for this simple thing...

As I think the most common solution is to keep them donloadable (one by one on demand) or just including them with the app (will make the app bigger a little but famous services are no more than 30 ones)

And if some users have concerns about network permission you can add an option in settings to allow downloading icons from internet (off by default) and give a detailed info about it in the app page (and actually the app is open source so anyone can check code)

**Comment by Ennneerrrgggyyy** [comment]
Thank you so much for the icons! Awesome job. Almost all I needed were included :)

Still missing:
XING
GMX
Epic Games
Boxcryptor
IFTTT
Kraken

**Comment by krisu5** [comment]
> Still missing:
> XING
> GMX
> Epic Games
> Boxcryptor
> IFTTT
> Kraken

[Done](https://drive.google.com/drive/folders/14pLZVLUw4FsC9zoQtuMnnA2gBXKYUCyW). 😃

**Comment by Ennneerrrgggyyy** [comment]
Oh that's awesome! Thank you krisu5 :)

**Comment by markcs** [comment]
Could the icons be embedded in a simple zip file that could be linked to and downloaded through the web browser.  => no internet permissions required.  

The user would select the zip file and Aegis would be able to identify which icons are included (maybe via a config file within the zip archive) and allow the user to extract those that they need.

**Comment by Wilker-a** [comment]
in either cases (if in-app or a separated), there could be an interface that acts like a file explorer (as in, it appears as an option to use when selecting an image) that actually just accesses the page and attempts to download the SVG to then send it back to the app for use.

i think it would reduce the app size if it were to do nothing but just list and download on demand (as in store what's already downloaded (and also delete later as needed) to just reuse and avoiding downloading again), and probably have its own interface to try to download less elements of the site? 

.. i guess all i am saying is just repeating what someone else said here earlier...

**Comment by MarioMasta64** [comment]
this is my only reason i have left not to use aegis over andotp (that and it would be cool if there was an icon grid mode like authy, i have almost 100 totp codes and its kinda painful to scroll through a bunch of iconless things because my images wont load)

**Comment by DarylSun** [comment]
Hello, thank you for your work! These icons are very lovely. I wonder if you will be able to make icons for these platforms in the future?

- Disroot
- Nextcloud
- Mailfence
- Mastodon
- SourceForge

**Comment by krisu5** [comment]
@DarylSun Done. Available at the repo.

I finally decided to make a repo for this project: https://github.com/krisu5/aegis-icons

Please add requests there from now on, I'm closing this issue.

**Comment by mmrabbani** [comment]
I think embed all icons of https://github.com/krisu5/aegis-icons is a great idea. beside this, it could be option of use image from user gallery. it can fix the problem of issues like "icon X is missing" or "icon X should be changed". problem of andOTP is that user cannot find icon out of the list.
another feature can be: Aegis app can automatically suggest icon according to issuer name. and if app cannot find icon, user can find it manually from embed list or user gallery.
