### ISSUE TITLE
QR Code Scanning not working [Xiaomi Poco M3]

### ISSUE THREAD

**Issue by DevSupporter** [beemdevelopment/Aegis#657]
###### Info

* __Version__: 1.4.1
* __Source__:  Google Play
* __Vault encrypted:__ Yes  
* __Device: Xioami Poco M3
* __Android version and ROM: 10 

###### Steps to reproduce

1.) Tap to scan a new QR Code --> Premission for camera allowed
2.) Camera opens up, but without "Scanning Frame" (Fullscreen preview of camera)
3.) No matter how close / far you go to an QR Code - no scan possible

--> All other Apps like Google Auth, Microsoft etc. are able to scan

###### What do you expect to happen?

Scan of QR Code

###### What happens instead?

Nothing - only preview of camera

**Comment by alexbakker** [comment]
Are you sure you're seeing this issue on 1.4.1? There was an issue in 1.4 with QR code scanning, but after the release of 1.4.1 all other feedback suggests that the issue was fixed.

In case you're sure: could you capture a log with ADB and share it? We have a guide on how to do so here: https://github.com/beemdevelopment/Aegis/blob/master/CONTRIBUTING.md#capturing-a-log-with-adb.

**Comment by DevSupporter** [comment]
Yes I'm sure it's the latest version 1.4.1 (also read about your latest issues with the camera). I tried to debug the application but I failed to only log the aegis related stuff (so I have now a full debug log with probably lots of confidential informations?).  So may you help me which parts are relevant? 

I looked for "camera" 

01-06 17:56:43.717  1612  2620 D CompatibilityInfo: applicationDensity - 440
01-06 17:56:43.717  1612  2620 D CompatibilityInfo: applicationScale - 1.0
01-06 17:56:43.722  1612  2620 I Timeline: Timeline: App_transition_ready time:98090043
01-06 17:56:43.725 25704 25704 W ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@c5d7714
01-06 17:56:43.758 25704 25929 I CameraManagerGlobal: Connecting to camera service
01-06 17:56:43.764   734 25853 D         : updateNewAdValue received dataLux: 1
01-06 17:56:43.764   734 25853 D         : updateNewAdValue getSLSLevel: 0
01-06 17:56:43.764   734 25853 D         : updateNewAdValue levelDiff: 0
01-06 17:56:43.767  1612  3596 I Timeline: Timeline: App_transition_ready time:98090088
01-06 17:56:43.769  1612  3596 I Timeline: Timeline: App_transition_ready time:98090090
01-06 17:56:43.781  1035 25146 W ServiceManager: Permission failure: android.permission.CAMERA_OPEN_CLOSE_LISTENER from uid=10268 pid=25704
01-06 17:56:43.782 25704 25929 W CameraManagerGlobal: [soar.cts] ignore the status update of camera: 2
01-06 17:56:43.782 25704 25929 W CameraManagerGlobal: [soar.cts] ignore the status update of camera: 3
01-06 17:56:43.782 25704 25929 W CameraManagerGlobal: [soar.cts] ignore the status update of camera: 4
01-06 17:56:43.782 25704 25929 W CameraManagerGlobal: [soar.cts] ignore the status update of camera: 5
01-06 17:56:43.782 25704 25929 W CameraManagerGlobal: [soar.cts] ignore the status update of camera: 6
01-06 17:56:43.783 25704 25723 W CameraManagerGlobal: ignore the torch status update of camera: 3
01-06 17:56:43.783 25704 25723 W CameraManagerGlobal: ignore the torch status update of camera: 4
01-06 17:56:43.783 25704 25723 W CameraManagerGlobal: ignore the torch status update of camera: 5
01-06 17:56:43.788  1612  1758 I Timeline: Timeline: App_transition_ready time:98090109
01-06 17:56:43.795  1612  1784 I ActivityTaskManager: Displayed com.beemdevelopment.aegis/.ui.ScannerActivity: +99ms
01-06 17:56:43.798  3605  3605 I GoogleInputMethodService: GoogleInputMethodService.onFinishInput():3308 
01-06 17:56:43.799  3605  3605 I GoogleInputMethodService: GoogleInputMethodService.onStartInput():1887 
01-06 17:56:43.801  2114  2114 D StatusBar: disable<e i a s b h r c s > disable2<q i n g r >
01-06 17:56:43.802  2114  2114 D PhoneStatusBar/NavigationBarView: setDisabledFlags back:false home:false recent:false
01-06 17:56:43.802  2114  2114 D StatusBarClock:  isNormalMode= true clock visible=true
01-06 17:56:43.807 25704 25929 D CameraRepository: Added camera: 0
01-06 17:56:43.812 25704 25929 I Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_3
01-06 17:56:43.813  2114  2114 D PhoneStatusBar/NavigationBarView: onDraw
01-06 17:56:43.815 25704 25929 D CameraRepository: Added camera: 1
01-06 17:56:43.816 25704 25929 I Camera2CameraInfo: Device Level: INFO_SUPPORTED_HARDWARE_LEVEL_3
01-06 17:56:43.816 25704 25930 D UseCaseAttachState: Active and attached use case: [] for camera: 0
01-06 17:56:43.816 25704 25930 D UseCaseAttachState: Active and attached use case: [] for camera: 1

What I also can mentioned, as it is a Xioami phone I deactivated some bloatware (also like google lens etc.) and maybe this is causing the issue?

**Comment by Cohiba99** [comment]
If it helps, reading Aegis 1.4.1 QR codes works fine on my Xiaomi Poco X3 NFC running debloated MIUI 12.0.4

**Comment by alexbakker** [comment]
@DevSupporter Someone with exactly the same device reports that QR scanning is working for them. Do you have the same version of MIUI as @Cohiba99? If not, can you update to the latest version and see if that fixes the issue?

**Comment by DevSupporter** [comment]
The phone is running on MIUI 12.0.5, so the latest version. Cohiba99 was writing about the Poco X3, but I have the issue with the Poco M3. I also installed an GCam addaption for the phone, but I already tried to uninstall und retry but still have the issue. I tried several other Apps, like andotp, TOTP Authenticator etc. and they all work. Only for Aegis (which I want to use) the issue with the missing viewfinder / QR Code scanning is happening

**Comment by alexbakker** [comment]
Ah my bad, I misread your message, X3 and M3 look very similar.

> Only for Aegis (which I want to use) the issue with the missing viewfinder / QR Code scanning is happening

There is no viewfinder, the preview you're seeing is what all other user also see. I guess we can write a debug patch to see what the picture your phone is taking through CameraX looks like.

**Comment by DevSupporter** [comment]
Yes no problem (about X3 / M3) that's why I just pointed it out. 

Good to know that there is no "viewfinder". But I tried again with several QR-Codes, it just does not scan it. How could you provide me the patch so that I can test it?

**Comment by alexbakker** [comment]
I'll have to write it and provide your with an APK.

**Comment by CryptoSlob** [comment]
I am having the same issue with a Motorola G7 power.  I am on version 1.4.1 as well.

**Comment by TransientResponse** [comment]
Same issue with OnePlus 7Pro, Oxygen OS 10.3.7. Tested app versions 1.3, 1.4, 1.4.1 and 1.4.2.

**Comment by alexbakker** [comment]
Let's try [forcing CameraX to target a higher resolution](https://github.com/alexbakker/Aegis/commit/e19fe8acf276bb3f464720ec86dfbfa9d84c0960). Can those who experience this issue try the following debug APK and report back: https://alexbakker.me/u/c1mv100j2u.apk?

**Comment by TransientResponse** [comment]
For my part, that didn't work either. I generated a test code from http://security-totp.appspot.com and your debug APK didn't detect it. But release 1.4.2 from the Play Store does. I can continue on with the Play Store version, but I'm happy to test things to help other people get theirs working.

**Comment by alexbakker** [comment]
@TransientResponse 

If 1.4.2 is able to scan QR codes, then so should 1.4.1, because no changes to the scanner were made since then. It's surprising that the debug APK doesn't work for you though. On my device, it's able to detect QR codes at much greater distances now. Curious what others' findings are.

> but still does not display the "viewfinder"

There is no view finder, it will try to detect QR codes visible anywhere in the camera preview.

**Comment by DevSupporter** [comment]
Just short feedback from my side (little bit on a hurry): I downloaded the APK with the higher resolution for the cam, but it did not changed anything. Still scanning or QR Code is not possible (tried several ones and also the generator posted above). I also retry with the new version 1.4.2 but also here nothing changed for me (Poco M3)

**Comment by Brian-Chow** [comment]
I'm not sure if this is the same issue, or a different one.  It's related to both this and issue #677 in that I have extreme difficulty scanning QR codes, especially dark mode ones, but not always just dark mode.  Using a OnePlus 9 OxygenOS 11.2.2.2 --  I would say...80% of the time I can't pick up a barcode from within Aegis.  What I find interesting is that Binary Eye (FOSS -- F-Droid, Github, and Google Play) can, 100% of the time, pick up barcodes that Aegis doesn't, and it also uses ZXing for it's engine.

**Comment by alexbakker** [comment]
@Brian-Chow Can you try the APK linked here: https://github.com/beemdevelopment/Aegis/issues/657#issuecomment-763076785? Does it improve the situation at all?

**Comment by Brian-Chow** [comment]
> @Brian-Chow Can you try the APK linked here: [#657 (comment)](https://github.com/beemdevelopment/Aegis/issues/657#issuecomment-763076785)? Does it improve the situation at all?

I haven't had a chance to test exhaustively, but so far, in my limited testing, no, it seems the be the same.  Either both the google play and dev version pick up the QR, or neither does.

**Comment by alexbakker** [comment]
For anyone still not able to scan QR codes with Aegis at all, please see: https://github.com/beemdevelopment/Aegis/issues/726#issuecomment-831570836.

**Comment by terriyu** [comment]
Encountering the same bug.

Aegis version: 2.0.3
Device: Google Pixel 4
Android version: 11

Behavior:
When I try to scan a new QR code, the camera opens but no QR code is scanned.

Behavior:
If instead I try to scan from image using a photo of the QR code, I get "An error occured. Unable to read and process QR code. com.google.zxing.NotFoundException"

Additional notes:
I was able to scan the same QR code using a different authenticator app (Google Authenticator).
